.TH "doxample.c" 1 "31 Jul 2004" "doxample-0.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doxample.c \- 
.SH "Detailed Description"
.PP 
Main Doxygen/Autotools integration example program. 


.PP
.SH SYNOPSIS
.br
.PP
\fC#include 'config.h'\fP
.br
\fC#include <stdio.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, int argv)"
.br
.RI "\fIMain Doxygen/Autotools integration example program. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, int argv)"
.PP
Main Doxygen/Autotools integration example program. \fBParameters:\fP
.RS 4
\fIargc\fP Number of command line options. 
.br
\fIargv\fP The command line options. 
.RE
.PP
\fBReturns:\fP
.RS 4
The exit status. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for doxample-0.1 from the source code.
