#!/bin/bash

if [ "x${SOS_ROOT}" == "x" ] ; then
  echo "Please set the SOS_ROOT environment variable."
  kill -INT $$
fi
if [ "x${SOS_WORK}" == "x" ] ; then
  echo "Please set the SOS_WORK environment variable."
  kill -INT $$
fi
if [ "x${SOS_CMD_PORT}" == "x" ] ; then
  echo "Please set the SOS_CMD_PORT environment variable."
  kill -INT $$
fi

valgrind --leak-check=full --show-leak-kinds=all ${SOS_ROOT}/bin/test $1
#valgrind --leak-check=full ${SOS_ROOT}/bin/test $1
