include "sos.h"

int main(void) {
SOS_runtime * _runtime = NULL;
SOS_init(&_runtime, SOS_ROLE_CLIENT, SOS_RECEIVES_NO_FEEDBACK, NULL);
char pub_name[SOS_DEFAULT_STRING_LEN] = {0};
char app_version[SOS_DEFAULT_STRING_LEN] = {0};
_runtime->config.comm_rank = 0;
_runtime->config.comm_size = 1;
sprintf(pub_name, "TAU_SOS_SUPPORT");
sprintf(app_version, "v0.alpha");
SOS_pub *tau_sos_pub = NULL;
SOS_pub_init(_runtime, &tau_sos_pub, pub_name, SOS_NATURE_DEFAULT);
SOS_pub_config(tau_sos_pub, SOS_PUB_OPTION_CACHE, 20);
SOS_announce(tau_sos_pub);
long value;
int ivalue;
double dvalue;
char name[256];
char svalue[256];
unsigned long int instance_guid = tau_sos_pub->guid;
SOS_pack(tau_sos_pub, "TAU:MPI:INSTANCE_ID", SOS_VAL_TYPE_LONG, &instance_guid);
strcpy(name,"TAU_EVENT_ENTRY:0:.TAU application");
value = 1673464656;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:int main(int, char **) [{lulesh.cc} {2691,1}-{2818,1}]");
value = 1673464826;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Init()");
value = 1673465166;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_Metadata:0:CPU Cores");
strcpy(svalue,"4");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:CPU MHz");
strcpy(svalue,"2000.000");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:CPU Type");
strcpy(svalue,"Intel(R) Xeon(R) CPU X5355 @ 2.66GHz");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:CPU Vendor");
strcpy(svalue,"GenuineIntel");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:CWD");
strcpy(svalue,"/home/khuck/src/lulesh");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Cache Size");
strcpy(svalue,"4096 KB");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Command Line");
strcpy(svalue,"./lulesh2.0 -q -i 100");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Executable");
strcpy(svalue,"/home/khuck/src/lulesh/lulesh2.0");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Hostname");
strcpy(svalue,"ktau");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Local Time");
strcpy(svalue,"2018-07-18T17:37:53-07:00");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Memory Size");
strcpy(svalue,"8172388 kB");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Node Name");
strcpy(svalue,"ktau");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:OS Machine");
strcpy(svalue,"x86_64");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:OS Name");
strcpy(svalue,"Linux");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:OS Release");
strcpy(svalue,"4.4.0-130-generic");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:OS Version");
strcpy(svalue,"#156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Starting Timestamp");
strcpy(svalue,"1531960673371409");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU Architecture");
strcpy(svalue,"default");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU Config");
strcpy(svalue," -iowrapper -pdt=/home/khuck/install/pdtoolkit-3.25 -papi=/usr/local/papi/5.5.0 -sos=/home/khuck/install/sos_flow -mpi -adios=/home/khuck/src/ADIOS/ADIOS-gcc");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU Makefile");
strcpy(svalue,"/home/khuck/src/tau2/x86_64/lib/Makefile.tau-papi-mpi-pthread-pdt-sos-adios");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU Version");
strcpy(svalue,"2.26.1-git");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_BFD_LOOKUP");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_CALLPATH");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_CALLPATH_DEPTH");
strcpy(svalue,"100");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_CALLSITE_DEPTH");
strcpy(svalue,"1");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_COMM_MATRIX");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_COMPENSATE");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_CUDA_BINARY_EXE");
strcpy(svalue,"");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_CUPTI_API");
strcpy(svalue,"runtime");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_INCLUSIVE");
strcpy(svalue,"0 usec");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_KEEP_UNRESOLVED_ADDR");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_PERIOD");
strcpy(svalue,"10000");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_IBM_BG_HWP_COUNTERS");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_MAX_THREADS");
strcpy(svalue,"128");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_MEASURE_TAU");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_MEMDBG_PROTECT_ABOVE");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_MEMDBG_PROTECT_BELOW");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_MEMDBG_PROTECT_FREE");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_OPENMP_RUNTIME");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_OPENMP_RUNTIME_EVENTS");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_OPENMP_RUNTIME_STATES");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_OUTPUT_CUDA_CSV");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_PAPI_MULTIPLEXING");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_PROFILE");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_PROFILE_FORMAT");
strcpy(svalue,"merged");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_SAMPLING");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_SHOW_MEMORY_FUNCTIONS");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_SIGNALS_GDB");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_THROTTLE");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_THROTTLE_NUMCALLS");
strcpy(svalue,"100000");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_THROTTLE_PERCALL");
strcpy(svalue,"10");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACE");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACE_FORMAT");
strcpy(svalue,"tau");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_CUDA_CDP");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_CUDA_INSTRUCTIONS");
strcpy(svalue,"");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_CUDA_SASS");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_HEADROOM");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_HEAP");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_IO_PARAMS");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_MEMORY_FOOTPRINT");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_MEMORY_LEAKS");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_MESSAGE");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_SIGNALS");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_TRACK_UNIFIED_MEMORY");
strcpy(svalue,"off");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Timestamp");
strcpy(svalue,"1531960673371514");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:UTC Time");
strcpy(svalue,"2018-07-19T00:37:53Z");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:pid");
strcpy(svalue,"2415");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:tid");
strcpy(svalue,"2415");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:username");
strcpy(svalue,"khuck");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Init()");
value = 1673496937;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_Metadata:0:MPI Processor Name");
strcpy(svalue,"ktau");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:CRAY_CORE_ID");
strcpy(svalue,"0");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_EVENT_COUNTER:0:Heap Memory Used (KB)");
value = 92213;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Memory Footprint (VmRSS) (KB)");
value = 25816;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 25816;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
strcpy(name,"TAU_EVENT_ENTRY:1:.TAU application");
value = 1673497738;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Comm_size()");
value = 1673498919;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Comm_size()");
value = 1673499592;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Comm_rank()");
value = 1673499774;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Comm_rank()");
value = 1673499941;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Comm_rank()");
value = 1673508292;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Comm_rank()");
value = 1673508412;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Barrier()");
value = 1673511353;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Barrier()");
value = 1673511611;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673544126;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673551563;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1673576970;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1673577584;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673609505;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673616760;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1673641756;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1673641902;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673672219;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673679517;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1673704511;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1673704664;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673735045;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673742348;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1673767400;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1673767540;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673797975;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673805236;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1673830144;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1673830280;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673860526;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673867836;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1673892884;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1673893021;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673923507;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673930845;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1673955925;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1673956064;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673986437;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1673993711;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674018730;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674018867;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674049382;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674056685;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674081669;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674081804;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674112046;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674119346;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674144598;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674144743;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674175087;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674182327;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674207309;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674207446;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674237867;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674245124;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674270131;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674270268;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674300753;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674308044;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674333075;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674333209;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674363437;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674370751;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674395761;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674395896;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674426253;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674433559;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674458619;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674458754;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674489242;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674496499;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Heap Memory Used (KB)");
value = 102985;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Memory Footprint (VmRSS) (KB)");
value = 40712;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 48936;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674522850;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674522990;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674553329;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674560617;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674585702;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674585840;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674616246;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674623538;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674648711;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674648845;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674679191;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674686431;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674711555;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674711692;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674742041;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674749321;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674774375;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674774515;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674804927;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674812151;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674837213;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674837347;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674867632;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674874973;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674899951;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674900091;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674930469;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674937767;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1674962832;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1674962971;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1674993366;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675000646;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675025707;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675025853;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675056316;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675063565;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675088669;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675088801;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675119209;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675126489;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675151548;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675151687;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675181929;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675189255;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675214231;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675214371;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675244660;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675251868;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675276897;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675277033;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675307271;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675314556;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675339554;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675339691;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675369967;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675377175;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675402214;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675402351;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675432659;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675439926;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675464987;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675465121;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675495421;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Heap Memory Used (KB)");
value = 102985;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Memory Footprint (VmRSS) (KB)");
value = 40740;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 48936;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675503642;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675529148;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675529291;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675559647;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675566899;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675592359;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675592547;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675622820;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675630103;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675655165;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675655300;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675685566;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675692869;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675717963;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675718099;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675748320;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675755578;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675780653;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675780786;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675810989;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675818269;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675843388;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675843520;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675873762;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675881025;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675906063;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675906199;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675936457;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675943756;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1675968845;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1675968986;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1675999227;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676006469;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676031549;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676031693;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676061947;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676069249;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676094269;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676094404;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676124734;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676131962;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676156992;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676157127;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676187343;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676194651;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676219705;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676219846;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676250115;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676257355;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676282410;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676282546;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676312796;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676320025;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676345110;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676345242;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676375494;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676382766;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676407931;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676408067;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676438384;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676445662;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676470710;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676470848;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Heap Memory Used (KB)");
value = 102775;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Memory Footprint (VmRSS) (KB)");
value = 40768;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 48948;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676502259;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676509609;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676534786;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676534925;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676565170;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676572419;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676597583;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676597752;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676628051;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676635266;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676660392;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676660558;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676690752;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676698075;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676723167;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676723309;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676753546;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676760817;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676785911;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676786052;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676816229;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676823485;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676848632;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676848764;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676879033;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676886316;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676911450;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676911583;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676941834;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1676949132;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1676974224;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1676974368;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677004693;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677011950;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677037133;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677037274;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677067500;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677074820;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677099929;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677100077;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677130246;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677137473;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677162576;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677162716;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677192919;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677200187;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677225264;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677225401;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677255619;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677262903;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677287997;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677288134;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677318296;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677325567;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677350671;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677350803;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677381059;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677388338;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677413453;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677413593;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677443765;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677451015;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677476116;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677476255;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Heap Memory Used (KB)");
value = 113744;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Memory Footprint (VmRSS) (KB)");
value = 48972;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 48972;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677507359;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677514707;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677539759;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677539908;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677569947;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677577215;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677602337;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677602478;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677632631;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677639911;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677665044;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677665186;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677695194;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677702471;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677727533;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677727681;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677757786;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677765049;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677790117;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677790258;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677820204;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677827487;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677852564;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677852707;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677882739;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677890046;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677915114;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677915252;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677945312;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1677952564;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1677977581;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1677977757;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678007817;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678015050;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678040334;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678040519;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678070533;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678077850;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678102892;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678103035;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678133284;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678140625;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678165694;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678165836;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678195841;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678203131;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678228184;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678228323;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678258386;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678265612;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678290660;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678290800;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678320855;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678328097;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678353178;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678353318;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678383312;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678390627;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678415714;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678415858;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678445893;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678453185;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678478256;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678478401;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Heap Memory Used (KB)");
value = 113745;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Memory Footprint (VmRSS) (KB)");
value = 48996;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 48996;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678509456;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678516731;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678541861;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678542012;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678571995;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678579298;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678604414;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678604599;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678634666;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678641953;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678667068;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678667210;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678697259;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678704568;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678729839;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678729978;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678760003;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678767281;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678792425;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678792590;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678822602;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678829864;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678854958;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678855101;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678885157;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678892405;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678917550;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678917716;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678947788;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1678955070;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1678980165;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1678980309;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679010337;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679017595;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679042952;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679043101;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679073186;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679080441;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679105706;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679105849;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679135909;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679143191;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679168294;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679168434;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679198519;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679205760;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679230838;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679230981;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679261022;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679268319;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679293394;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679293538;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679323569;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679330900;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679355981;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679356121;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679386195;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679393442;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679418563;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679418706;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679448865;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679456104;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679481272;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679481416;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Heap Memory Used (KB)");
value = 113746;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Memory Footprint (VmRSS) (KB)");
value = 49024;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 49024;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:1:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679512355;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679519680;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679544854;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679544993;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679575051;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679582327;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679607497;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679607641;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679637806;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679645054;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679670203;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679670344;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679700410;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679707670;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Allreduce()");
value = 1679732999;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for all-reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Allreduce()");
value = 1679733134;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679763224;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:void CalcKinematicsForElems(Domain &, Real_t *, Real_t, Index_t) [{lulesh.cc} {1534,1}-{1597,1}]");
value = 1679770508;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Reduce()");
value = 1679795779;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Message size for reduce");
value = 8;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Reduce()");
value = 1679796020;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_ENTRY:0:MPI_Finalize()");
value = 1679796110;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_Metadata:0:Ending Timestamp");
strcpy(svalue,"1531960679704554");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:MPI Processor Name");
strcpy(svalue,"ktau");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_SAMPLES_TAKEN_0");
strcpy(svalue,"633");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_SAMPLES_DROPPED_TAU_0");
strcpy(svalue,"0");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_SAMPLES_DROPPED_SUSPENDED_0");
strcpy(svalue,"5");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_SAMPLES_TAKEN_1");
strcpy(svalue,"633");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_SAMPLES_DROPPED_TAU_1");
strcpy(svalue,"0");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_EBS_SAMPLES_DROPPED_SUSPENDED_1");
strcpy(svalue,"5");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU Unification Time");
strcpy(svalue,"0.002062 seconds");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU Unification Time");
strcpy(svalue,"1.8E-05 seconds");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Ending Timestamp");
strcpy(svalue,"1531960679704554");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Ending Timestamp");
strcpy(svalue,"1531960679704554");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU Profile Merge Time");
strcpy(svalue,"0.001527 seconds");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:TAU_PRECOMPUTE");
strcpy(svalue,"on");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_Metadata:0:Ending Timestamp");
strcpy(svalue,"1531960679704554");
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_STRING, svalue);
strcpy(name,"TAU_EVENT_COUNTER:0:Heap Memory Used (KB)");
value = 171215;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Memory Footprint (VmRSS) (KB)");
value = 97464;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:Peak Memory Usage Resident Set Size (VmHWM) (KB)");
value = 97464;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_COUNTER:0:System load");
value = 0;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
strcpy(name,"TAU_EVENT_EXIT:0:MPI_Finalize()");
value = 1679896272;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:int main(int, char **) [{lulesh.cc} {2691,1}-{2818,1}]");
value = 1679896342;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:1:.TAU application");
value = 1679899239;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
strcpy(name,"TAU_EVENT_EXIT:0:.TAU application");
value = 1679899271;
SOS_pack(tau_sos_pub, name, SOS_VAL_TYPE_LONG, &value);
SOS_announce(tau_sos_pub);
SOS_publish(tau_sos_pub);
SOS_finalize(_runtime);
}

