#!/bin/bash
if [ "x${SOS_ROOT}" == "x" ] ; then
  echo "Please set the SOS_ROOT environment variable."
  kill -INT $$
fi
if [ "x${SOS_WORK}" == "x" ] ; then
  echo "Please set the SOS_WORK environment variable."
  kill -INT $$
fi
if [ "x${SOS_CMD_PORT}" == "x" ] ; then
  echo "Please set the SOS_CMD_PORT environment variable."
  kill -INT $$
fi
if [ -z $1 ]; then echo ""; echo "*** Removing any files left by previous sosd daemons..."; echo ""; fi;
${SOS_ROOT}/src/mpi.cleanall
if [ -z $1 ]; then echo ""; echo "*** Launching the sosd daemons..."; echo ""; fi;
killall mpirun
echo ""
echo ""
# ###
# ###
valgrind_server=" gdb --args "
#valgrind_server=" valgrind "
#valgrind_server=" ${valgrind_server} --vgdb=yes                               "
#valgrind_server=" ${valgrind_server} --vgdb-error=0                           "
#valgrind_server=" ${valgrind_server} --tool=memcheck                          "
#valgrind_server=" ${valgrind_server} --leak-check=full                        "
#valgrind_server=" ${valgrind_server} --max-stackframe=3097792                 "
#valgrind_server=" ${valgrind_server} --show-reachable=yes                     "
#valgrind_server=" ${valgrind_server} --error-limit=no                         "
#valgrind_server=" ${valgrind_server} --log-file=${SOS_WORK}/sosd.valgrind.log "
#valgrind_server=" ${valgrind_server} --xml=yes                                "
#valgrind_server=" ${valgrind_server} --xml-file=${SOS_WORK}/sosd.valgrind.xml "
#valgrind_server=" ${valgrind_server} --show-leak-kinds=all                    "
#valgrind_server=" ${valgrind_server} --track-origins=yes                      "
#valgrind_server=" ${valgrind_server} --trace-children=yes                     "
# ###
sosd_daemon_cmd=" ${SOS_ROOT}/bin/sosd --role SOS_ROLE_DAEMON --port 22500 --buffer_len 8097152 --listen_backlog 10 --work_dir ${SOS_WORK} "
sosd_db_cmdline=" ${SOS_ROOT}/bin/sosd --role SOS_ROLE_DB     --port 22503 --buffer_len 8097152 --listen_backlog 10 --work_dir ${SOS_WORK} "
# ###
# ###


echo "Bringing up the [daemon]..."
echo ""
echo ""
mpirun -np 1 ${sosd_daemon_cmd} : -np 1 ${valgrind_server} ${sosd_db_cmdline}
echo ""
echo ""

echo ""
echo ""
echo "Done.  Valgrind processes still running:"
echo ""
echo ""
ps -eaf | grep "val"
echo ""
echo ""
