sos_flow-0.0: src/sos.h File Reference
sos.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/time.h>
#include <limits.h>
Data Structures
union SOS_val
struct SOS_time
struct SOS_meta
struct SOS_data
struct SOS_pub
struct SOS_sub
struct SOS_socket_set
struct SOS_config
struct SOS_uid
struct SOS_unique_set
struct SOS_ring_queue
struct SOS_ring_set
struct SOS_task_set
struct SOS_runtime
Macros
#define SOS_TIME(__SOS_now) { struct timeval t; gettimeofday(&t, NULL); __SOS_now = t.tv_sec + t.tv_usec/1000000.0; }
#define SOS_SET_WHOAMI(__SOS_var_name, __SOS_str_func)
#define SOS_STR_COPY_OF(__SOS_src_str, __SOS_tmp_str)
#define SOS_DEFAULT_LOCALHOST "localhost"
#define SOS_DEFAULT_BUFFER_LEN 1024000
#define SOS_DEFAULT_CMD_TIMEOUT 2048
#define SOS_DEFAULT_RING_SIZE 1024
#define SOS_DEFAULT_STRING_LEN 256
#define SOS_DEFAULT_UID_MAX LONG_MAX
#define SOS_DEFAULT_ELEM_COUNT 64
Typedefs
typedef enum SOS_whoami SOS_whoami
typedef enum SOS_state SOS_state
typedef enum SOS_msg_type SOS_msg_type
typedef enum SOS_pri SOS_pri
typedef enum SOS_val_type SOS_val_type
typedef enum SOS_val_state SOS_val_state
typedef enum SOS_val_sem SOS_sem
typedef enum SOS_scope SOS_scope
typedef enum SOS_layer SOS_layer
typedef enum SOS_nature SOS_nature
typedef enum SOS_retain SOS_retain
Enumerations
enum SOS_whoami { SOS_WHOAMI_CLIENT, SOS_WHOAMI_DAEMON, SOS_WHOAMI_LEADER, SOS_WHOAMI_CONTROL }
enum SOS_state { SOS_STATE_INIT, SOS_STATE_RUNNING, SOS_STATE_SHUTDOWN }
enum SOS_msg_type {
SOS_MSG_TYPE_ANNOUNCE, SOS_MSG_TYPE_REANNOUNCE, SOS_MSG_TYPE_VALUE, SOS_MSG_TYPE_ACKNOWLEDGE,
SOS_MSG_TYPE_SHUTDOWN
}
enum SOS_pri { SOS_PRI_DEFAULT, SOS_PRI_LOW, SOS_PRI_IMMEDIATE }
enum SOS_val_type { SOS_VAL_TYPE_LONG, SOS_VAL_TYPE_DOUBLE, SOS_VAL_TYPE_TEXT, SOS_VAL_TYPE_BLOB }
enum SOS_val_state { SOS_VAL_STATE_CLEAN, SOS_VAL_STATE_DIRTY, SOS_VAL_STATE_EMPTY }
enum SOS_val_sem {
SOS_VAL_SEM_TIME_START, SOS_VAL_SEM_TIME_STOP, SOS_VAL_SEM_TIME_STAMP, SOS_VAL_SEM_TIME_SPAN,
SOS_VAL_SEM_VAL_CURRENT, SOS_VAL_SEM_VAL_COUNTER
}
enum SOS_scope { SOS_SCOPE_DEFAULT, SOS_SCOPE_SELF, SOS_SCOPE_NODE, SOS_SCOPE_ENCLAVE }
enum SOS_layer {
SOS_LAYER_APP, SOS_LAYER_OS, SOS_LAYER_LIB, SOS_LAYER_FLOW,
SOS_LAYER_CONTROL
}
enum SOS_nature {
SOS_NATURE_CREATE_INPUT, SOS_NATURE_CREATE_OUTPUT, SOS_NATURE_CREATE_VIZ, SOS_NATURE_EXEC_WORK,
SOS_NATURE_BUFFER, SOS_NATURE_SUPPORT_EXEC, SOS_NATURE_SUPPORT_FLOW, SOS_NATURE_CONTROL_FLOW,
SOS_NATURE_SOS
}
enum SOS_retain { SOS_RETAIN_DEFAULT, SOS_RETAIN_SESSION, SOS_RETAIN_IMMEDIATE }
Functions
void SOS_init (int *argc, char ***argv, SOS_role role)
void SOS_finalize ()
long SOS_next_id (SOS_uid *uid)
void SOS_strip_str (char *str)
int SOS_pack (SOS_pub *pub, const char *name, SOS_type pack_type, SOS_val pack_val)
void SOS_repack (SOS_pub *pub, int index, SOS_val pack_val)
SOS_pub * SOS_new_pub (char *pub_name)
SOS_pub * SOS_new_post (char *pub_name)
void SOS_apply_announce (SOS_pub *pub, char *msg, int msg_len)
void SOS_apply_publish (SOS_pub *pub, char *msg, int msg_len)
void SOS_expand_data (SOS_pub *pub)
void SOS_get_val (SOS_pub *pub, char *name)
SOS_sub * SOS_new_sub ()
void SOS_free_pub (SOS_pub *pub)
void SOS_free_sub (SOS_sub *sub)
void SOS_display_pub (SOS_pub *pub, FILE *output_to)
void SOS_announce (SOS_pub *pub)
void SOS_publish (SOS_pub *pub)
void SOS_publish_immediately (SOS_pub *pub)
void SOS_send_to_daemon (char *msg, char *reply)
void SOS_unannounce (SOS_pub *pub)
SOS_sub * SOS_subscribe (SOS_role target_role, int target_rank, char *pub_title, int refresh_ms)
void SOS_unsubscribe (SOS_sub *sub)
Variables
SOS_runtime SOS
Macro Definition Documentation
#define SOS_DEFAULT_BUFFER_LEN 1024000
Definition at line 48 of file sos.h.
Referenced by SOS_init().
#define SOS_DEFAULT_CMD_TIMEOUT 2048
Definition at line 49 of file sos.h.
Referenced by SOS_init().
#define SOS_DEFAULT_ELEM_COUNT 64
Definition at line 53 of file sos.h.
#define SOS_DEFAULT_LOCALHOST "localhost"
Definition at line 47 of file sos.h.
Referenced by SOS_init().
#define SOS_DEFAULT_RING_SIZE 1024
Definition at line 50 of file sos.h.
Referenced by SOS_init().
#define SOS_DEFAULT_STRING_LEN 256
Definition at line 51 of file sos.h.
Referenced by main(), SOS_announce_to(), SOS_apply_publish(), SOS_pack(), and SOS_publish_to().
#define SOS_DEFAULT_UID_MAX LONG_MAX
Definition at line 52 of file sos.h.
#define SOS_SET_WHOAMI (__SOS_var_name, __SOS_str_func)
Value:
char __SOS_var_name[SOS_DEFAULT_STRING_LEN];                        \
    {                                                                   \
        memset(whoami, '\0', SOS_DEFAULT_STRING_LEN);                   \
        switch (SOS.role) {                                             \
        case SOS_CLIENT    : sprintf(__SOS_var_name, "client(%s).%s",  SOS.client_id, __SOS_str_func ); break; \
        case SOS_DAEMON    : sprintf(__SOS_var_name, "daemon(%s).%s",  SOS.client_id, __SOS_str_func ); break; \
        case SOS_LEADER    : sprintf(__SOS_var_name, "leader(%s).%s",  SOS.client_id, __SOS_str_func ); break; \
        case SOS_CONTROL   : sprintf(__SOS_var_name, "control(%s).%s", SOS.client_id, __SOS_str_func ); break; \
        default            : sprintf(__SOS_var_name, "------(%s).%s",  SOS.client_id, __SOS_str_func ); break; \
        }                                                               \
    }
Definition at line 28 of file sos.h.
Referenced by SOS_apply_announce(), SOS_expand_data(), SOS_finalize(), SOS_init(), SOS_new_post(), SOS_new_pub(), SOS_send_to_daemon(), SOS_THREAD_post(), SOS_THREAD_read(), and SOS_THREAD_scan().
#define SOS_STR_COPY_OF (__SOS_src_str, __SOS_tmp_str)
Value:
__SOS_tmp_str = malloc(1 + (sizeof(char) * strlen(__SOS_src_str))); \
    strcpy( __SOS_tmp_str, __SOS_src_str );
Definition at line 42 of file sos.h.
Referenced by SOS_new_post().
#define SOS_TIME (__SOS_now) { struct timeval t; gettimeofday(&t, NULL); __SOS_now = t.tv_sec + t.tv_usec/1000000.0; }
Definition at line 27 of file sos.h.
Referenced by SOS_apply_publish(), SOS_pack(), SOS_publish_to(), and SOS_repack().
Typedef Documentation
typedef enum SOS_layer SOS_layer
typedef enum SOS_msg_type SOS_msg_type
typedef enum SOS_nature SOS_nature
typedef enum SOS_pri SOS_pri
typedef enum SOS_retain SOS_retain
typedef enum SOS_scope SOS_scope
typedef enum SOS_val_sem SOS_sem
typedef enum SOS_state SOS_state
typedef enum SOS_val_state SOS_val_state
typedef enum SOS_val_type SOS_val_type
typedef enum SOS_whoami SOS_whoami
Enumeration Type Documentation
enum SOS_layer
Enumerator
SOS_LAYER_APP
SOS_LAYER_OS
SOS_LAYER_LIB
SOS_LAYER_FLOW
SOS_LAYER_CONTROL
Definition at line 114 of file sos.h.
enum SOS_msg_type
Enumerator
SOS_MSG_TYPE_ANNOUNCE
SOS_MSG_TYPE_REANNOUNCE
SOS_MSG_TYPE_VALUE
SOS_MSG_TYPE_ACKNOWLEDGE
SOS_MSG_TYPE_SHUTDOWN
Definition at line 71 of file sos.h.
enum SOS_nature
Enumerator
SOS_NATURE_CREATE_INPUT
SOS_NATURE_CREATE_OUTPUT
SOS_NATURE_CREATE_VIZ
SOS_NATURE_EXEC_WORK
SOS_NATURE_BUFFER
SOS_NATURE_SUPPORT_EXEC
SOS_NATURE_SUPPORT_FLOW
SOS_NATURE_CONTROL_FLOW
SOS_NATURE_SOS
Definition at line 122 of file sos.h.
enum SOS_pri
Enumerator
SOS_PRI_DEFAULT
SOS_PRI_LOW
SOS_PRI_IMMEDIATE
Definition at line 79 of file sos.h.
enum SOS_retain
Enumerator
SOS_RETAIN_DEFAULT
SOS_RETAIN_SESSION
SOS_RETAIN_IMMEDIATE
Definition at line 134 of file sos.h.
enum SOS_scope
Enumerator
SOS_SCOPE_DEFAULT
SOS_SCOPE_SELF
SOS_SCOPE_NODE
SOS_SCOPE_ENCLAVE
Definition at line 107 of file sos.h.
enum SOS_state
Enumerator
SOS_STATE_INIT
SOS_STATE_RUNNING
SOS_STATE_SHUTDOWN
Definition at line 65 of file sos.h.
enum SOS_val_sem
Enumerator
SOS_VAL_SEM_TIME_START
SOS_VAL_SEM_TIME_STOP
SOS_VAL_SEM_TIME_STAMP
SOS_VAL_SEM_TIME_SPAN
SOS_VAL_SEM_VAL_CURRENT
SOS_VAL_SEM_VAL_COUNTER
Definition at line 98 of file sos.h.
enum SOS_val_state
Enumerator
SOS_VAL_STATE_CLEAN
SOS_VAL_STATE_DIRTY
SOS_VAL_STATE_EMPTY
Definition at line 92 of file sos.h.
enum SOS_val_type
Enumerator
SOS_VAL_TYPE_LONG
SOS_VAL_TYPE_DOUBLE
SOS_VAL_TYPE_TEXT
SOS_VAL_TYPE_BLOB
Definition at line 85 of file sos.h.
enum SOS_whoami
Enumerator
SOS_WHOAMI_CLIENT
SOS_WHOAMI_DAEMON
SOS_WHOAMI_LEADER
SOS_WHOAMI_CONTROL
Definition at line 58 of file sos.h.
Function Documentation
void SOS_announce (SOS_pub * pub)
Definition at line 865 of file sos.c.
References SOS_announce_to(), and SOS_ICOMM_MONITOR.
void SOS_apply_announce (SOS_pub * pub, char * msg, int msg_len)
Definition at line 369 of file sos.c.
References SOS_pub::announced, SOS_val::c_val, SOS_pub::data, dlog, SOS_pub::elem_count, SOS_pub::elem_max, SOS_data::name, SOS_expand_data(), SOS_SET_WHOAMI, SOS_pub::title, SOS_data::type, and SOS_data::val.
Referenced by SOS_subscribe().
void SOS_apply_publish (SOS_pub * pub, char * msg, int msg_len)
Definition at line 468 of file sos.c.
References SOS_val::c_val, SOS_val::d_val, SOS_pub::data, SOS_data::dirty, dlog, SOS_pub::elem_count, SOS_val::i_val, SOS_val::l_val, SOS_DEBUG, SOS_DEFAULT_STRING_LEN, SOS_DOUBLE, SOS_LONG, SOS_TIME, SOS_warn_user, SOS_pub::title, SOS_data::type, and SOS_data::val.
Referenced by SOS_refresh_sub(), and SOS_subscribe().
void SOS_display_pub (SOS_pub * pub, FILE * output_to)
Definition at line 824 of file sos.c.
References SOS_val::c_val, SOS_val::d_val, SOS_pub::data, SOS_data::dirty, SOS_pub::elem_count, SOS_pub::elem_max, SOS_val::i_val, SOS_val::l_val, SOS_data::name, SOS_DEBUG, SOS_DOUBLE, SOS_LONG, SOS_pub::title, SOS_data::type, and SOS_data::val.
void SOS_expand_data (SOS_pub * pub)
Definition at line 313 of file sos.c.
References SOS_pub::data, SOS_pub::elem_max, and SOS_SET_WHOAMI.
Referenced by SOS_apply_announce(), and SOS_pack().
void SOS_finalize ()
Definition at line 129 of file sos.c.
References SOS_runtime::global_lock, SOS_ring_queue::heap, SOS_uid::lock, SOS_ring_queue::lock, SOS_task_set::post, SOS_unique_set::pub, SOS_task_set::read, SOS_ring_set::recv, SOS_runtime::ring, SOS_task_set::scan, SOS_ring_set::send, SOS_unique_set::seq, SOS, SOS_SET_WHOAMI, SOS_runtime::status, SOS_unique_set::sub, SOS_runtime::task, and SOS_runtime::uid.
void SOS_free_pub (SOS_pub * pub)
Definition at line 808 of file sos.c.
void SOS_free_sub (SOS_sub * sub)
Definition at line 815 of file sos.c.
Referenced by SOS_unsubscribe().
void SOS_get_val (SOS_pub * pub, char * name)
Definition at line 785 of file sos.c.
References SOS_pub::data, SOS_pub::elem_count, SOS_data::name, and SOS_data::val.
void SOS_init (int * argc, char *** argv, SOS_role role)
Definition at line 48 of file sos.c.
References SOS_config::argc, SOS_config::argv, SOS_ring_queue::bytes, SOS_runtime::client_id, SOS_runtime::config, dlog, SOS_ring_queue::heap, SOS_uid::last, SOS_uid::lock, SOS_ring_queue::lock, SOS_uid::next, SOS_task_set::post, SOS_unique_set::pub, SOS_task_set::read, SOS_ring_queue::read_pos, SOS_ring_set::recv, SOS_runtime::ring, SOS_runtime::role, SOS_task_set::scan, SOS_ring_set::send, SOS_unique_set::seq, SOS_ring_queue::size, SOS, SOS_DEFAULT_BUFFER_LEN, SOS_DEFAULT_CMD_TIMEOUT, SOS_DEFAULT_LOCALHOST, SOS_DEFAULT_RING_SIZE, SOS_SET_WHOAMI, SOS_THREAD_post(), SOS_THREAD_read(), SOS_runtime::status, SOS_unique_set::sub, SOS_runtime::task, SOS_runtime::uid, and SOS_ring_queue::write_pos.
SOS_pub* SOS_new_post (char * pub_name)
Definition at line 255 of file sos.c.
References SOS_pub::announced, SOS_meta::channel, SOS_runtime::config, SOS_pub::data, SOS_data::dirty, SOS_pub::elem_count, SOS_pub::elem_max, SOS_data::guid, SOS_val::l_val, SOS_meta::layer, SOS_data::len, SOS_pub::meta, SOS_data::name, SOS_meta::nature, SOS_config::node_id, SOS_time::pack, SOS_meta::pragma_len, SOS_meta::pragma_msg, SOS_meta::pri_hint, SOS_unique_set::pub, SOS_time::recv, SOS_meta::retain_hint, SOS_meta::scope_hint, SOS_meta::sem_hint, SOS_time::send, SOS, SOS_LAYER_APP, SOS_next_id(), SOS_PRI_DEFAULT, SOS_RETAIN_DEFAULT, SOS_SCOPE_DEFAULT, SOS_SET_WHOAMI, SOS_STR_COPY_OF, SOS_data::time, SOS_pub::title, SOS_data::type, SOS_runtime::uid, and SOS_data::val.
SOS_pub* SOS_new_pub (char * pub_name)
Definition at line 218 of file sos.c.
References dlog, and SOS_SET_WHOAMI.
Referenced by main(), and SOS_new_sub().
SOS_sub* SOS_new_sub ()
Definition at line 797 of file sos.c.
References SOS_sub::active, SOS_sub::pub, and SOS_new_pub().
Referenced by SOS_subscribe().
long SOS_next_id (SOS_uid * uid)
int SOS_pack (SOS_pub * pub, const char * name, SOS_type pack_type, SOS_val pack_val)
Definition at line 568 of file sos.c.
References SOS_pub::announced, SOS_val::c_val, SOS_pub::data, SOS_data::dirty, dlog, SOS_pub::elem_count, SOS_pub::elem_max, SOS_val::i_val, SOS_val::l_val, SOS_data::name, SOS_DEFAULT_STRING_LEN, SOS_DOUBLE, SOS_expand_data(), SOS_LONG, SOS_TIME, SOS_data::type, and SOS_data::val.
void SOS_publish (SOS_pub * pub)
Definition at line 871 of file sos.c.
References SOS_ICOMM_MONITOR, and SOS_publish_to().
void SOS_publish_immediately (SOS_pub * pub)
void SOS_repack (SOS_pub * pub, int index, SOS_val pack_val)
Definition at line 748 of file sos.c.
References SOS_val::c_val, SOS_pub::data, SOS_data::dirty, SOS_DOUBLE, SOS_LONG, SOS_TIME, SOS_data::type, and SOS_data::val.
void SOS_send_to_daemon (char * msg, char * reply)
Definition at line 114 of file sos.c.
References SOS_SET_WHOAMI.
void SOS_strip_str (char * str)
Definition at line 355 of file sos.c.
SOS_sub* SOS_subscribe (SOS_role target_role, int target_rank, char * pub_title, int refresh_ms)
Definition at line 1202 of file sos.c.
References SOS_sub::pub, SOS_sub::refresh_delay, SOS_apply_announce(), SOS_apply_publish(), SOS_COMM_LOCAL, SOS_ICOMM_APP, SOS_ICOMM_MONITOR, SOS_ICOMM_POWSCHED, SOS_new_sub(), SOS_refresh_sub(), SOS_warn_user, SOS_sub::source_rank, SOS_sub::source_role, SOS_sub::suid, and SOS_sub::thread_handle.
void SOS_unannounce (SOS_pub * pub)
Definition at line 1187 of file sos.c.
void SOS_unsubscribe (SOS_sub * sub)
Definition at line 1334 of file sos.c.
References SOS_sub::active, SOS_free_sub(), SOS_sub::suid, and SOS_sub::thread_handle.
Variable Documentation
SOS_runtime SOS
Definition at line 272 of file sos.h.
Referenced by SOS_finalize(), SOS_init(), SOS_new_post(), SOS_THREAD_post(), SOS_THREAD_read(), and SOS_THREAD_scan().