sos_flow-0.0: src/sos.c File Reference
sos.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>
#include <sys/types.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <netdb.h>
#include "sos.h"
#include "sos_debug.h"
Functions
void * SOS_THREAD_post (void *arg)
void * SOS_THREAD_read (void *arg)
void * SOS_THREAD_scan (void *arg)
void SOS_post_to_daemon (char *msg, char *reply)
void SOS_free_pub (SOS_pub *pub)
void SOS_free_sub (SOS_sub *sub)
void SOS_expand_data (SOS_pub *pub)
void SOS_init (int *argc, char ***argv, SOS_role role)
void SOS_send_to_daemon (char *msg, int msg_len, char *reply, int max_reply_size)
void SOS_finalize ()
long SOS_next_id (SOS_uid *id)
SOS_pub * SOS_new_pub (char *title)
SOS_pub * SOS_new_post (char *title)
void SOS_strip_str (char *str)
void SOS_apply_announce (SOS_pub *pub, char *msg, int msg_size)
void SOS_apply_publish (SOS_pub *pub, char *msg, int msg_len)
int SOS_pack (SOS_pub *pub, const char *name, SOS_val_type pack_type, SOS_val pack_val)
void SOS_repack (SOS_pub *pub, int index, SOS_val pack_val)
SOS_val SOS_get_val (SOS_pub *pub, char *name)
SOS_sub * SOS_new_sub ()
void SOS_display_pub (SOS_pub *pub, FILE *output_to)
void SOS_announce (SOS_pub *pub)
void SOS_publish (SOS_pub *pub)
void SOS_unannounce (SOS_pub *pub)
SOS_sub * SOS_subscribe (SOS_role source_role, int source_rank, char *pub_title, int refresh_delay)
void * SOS_refresh_sub (void *arg)
void SOS_unsubscribe (SOS_sub *sub)
Function Documentation
void SOS_announce (SOS_pub * pub)
Definition at line 922 of file sos.c.
References SOS_pub::announced, SOS_pub::comm_rank, SOS_pub::data, dlog, SOS_pub::elem_count, SOS_data::guid, SOS_pub::meta, SOS_data::name, SOS_meta::nature, SOS_pub::prog_name, SOS_pub::pub_id, SOS_runtime::role, SOS, SOS_DEFAULT_BUFFER_LEN, SOS_ROLE_CLIENT, SOS_SET_WHOAMI, SOS_pub::title, and SOS_data::type.
Referenced by SOS_publish().
void SOS_apply_announce (SOS_pub * pub, char * msg, int msg_size)
Definition at line 449 of file sos.c.
References SOS_pub::announced, SOS_val::c_val, SOS_pub::comm_rank, SOS_pub::data, dlog, SOS_pub::elem_count, SOS_pub::elem_max, SOS_data::guid, SOS_pub::meta, SOS_data::name, SOS_meta::nature, SOS_pub::prog_name, SOS_pub::pub_id, SOS_expand_data(), SOS_SET_WHOAMI, SOS_VAL_TYPE_STRING, SOS_pub::title, SOS_data::type, and SOS_data::val.
void SOS_apply_publish (SOS_pub * pub, char * msg, int msg_len)
Definition at line 549 of file sos.c.
References SOS_val::c_val, SOS_val::d_val, SOS_pub::data, dlog, SOS_pub::elem_count, SOS_val::i_val, SOS_val::l_val, SOS_time::pack, SOS_time::recv, SOS_runtime::role, SOS_time::send, SOS, SOS_DEBUG, SOS_ROLE_CONTROL, SOS_SET_WHOAMI, SOS_TIME, SOS_VAL_STATE_DIRTY, SOS_VAL_TYPE_DOUBLE, SOS_VAL_TYPE_INT, SOS_VAL_TYPE_LONG, SOS_VAL_TYPE_STRING, SOS_data::state, SOS_data::time, SOS_pub::title, SOS_data::type, and SOS_data::val.
void SOS_display_pub (SOS_pub * pub, FILE * output_to)
Definition at line 881 of file sos.c.
References SOS_val::c_val, SOS_pub::comm_rank, SOS_val::d_val, SOS_pub::data, SOS_pub::elem_count, SOS_pub::elem_max, SOS_data::guid, SOS_val::i_val, SOS_val::l_val, SOS_data::name, SOS_pub::prog_name, SOS_DEBUG, SOS_VAL_STATE_DIRTY, SOS_VAL_TYPE_DOUBLE, SOS_VAL_TYPE_INT, SOS_VAL_TYPE_LONG, SOS_VAL_TYPE_STRING, SOS_data::state, SOS_pub::title, SOS_data::type, and SOS_data::val.
void SOS_expand_data (SOS_pub * pub)
Definition at line 393 of file sos.c.
References SOS_pub::data, SOS_pub::elem_max, SOS_DEFAULT_ELEM_COUNT, and SOS_SET_WHOAMI.
Referenced by SOS_apply_announce(), and SOS_pack().
void SOS_finalize ()
Definition at line 206 of file sos.c.
References SOS_runtime::global_lock, SOS_ring_queue::heap, SOS_uid::lock, SOS_ring_queue::lock, SOS_runtime::net, SOS_task_set::post, SOS_unique_set::pub, SOS_task_set::read, SOS_ring_set::recv, SOS_runtime::ring, SOS_runtime::role, SOS_task_set::scan, SOS_ring_set::send, SOS_unique_set::seq, SOS_socket_set::server_addr, SOS, SOS_ROLE_CLIENT, SOS_SET_WHOAMI, SOS_STATUS_SHUTDOWN, SOS_runtime::status, SOS_unique_set::sub, SOS_runtime::task, and SOS_runtime::uid.
void SOS_free_pub (SOS_pub * pub)
Definition at line 865 of file sos.c.
void SOS_free_sub (SOS_sub * sub)
Definition at line 872 of file sos.c.
SOS_val SOS_get_val (SOS_pub * pub, char * name)
Definition at line 842 of file sos.c.
References SOS_pub::data, SOS_pub::elem_count, SOS_data::name, and SOS_data::val.
void SOS_init (int * argc, char *** argv, SOS_role role)
Definition at line 46 of file sos.c.
References SOS_config::argc, SOS_config::argv, SOS_socket_set::buffer_len, SOS_ring_queue::bytes, SOS_runtime::client_id, SOS_runtime::config, dlog, SOS_ring_queue::heap, SOS_uid::last, SOS_uid::lock, SOS_ring_queue::lock, SOS_runtime::net, SOS_uid::next, SOS_task_set::post, SOS_unique_set::pub, SOS_task_set::read, SOS_ring_queue::read_pos, SOS_ring_set::recv, SOS_socket_set::result_list, SOS_runtime::ring, SOS_runtime::role, SOS_task_set::scan, SOS_ring_set::send, SOS_unique_set::seq, SOS_socket_set::server_addr, SOS_socket_set::server_hint, SOS_socket_set::server_host, SOS_socket_set::server_port, server_socket_fd, SOS_ring_queue::size, SOS, SOS_DEFAULT_BUFFER_LEN, SOS_DEFAULT_MSG_TIMEOUT, SOS_DEFAULT_RING_SIZE, SOS_DEFAULT_SERVER_HOST, SOS_DEFAULT_UID_MAX, SOS_ROLE_CLIENT, SOS_SET_WHOAMI, SOS_STATUS_INIT, SOS_THREAD_post(), SOS_THREAD_read(), SOS_THREAD_scan(), SOS_runtime::status, SOS_unique_set::sub, SOS_runtime::task, SOS_socket_set::timeout, SOS_runtime::uid, and SOS_ring_queue::write_pos.
SOS_pub* SOS_new_post (char * title)
Definition at line 336 of file sos.c.
References SOS_pub::announced, SOS_meta::channel, SOS_pub::comm_rank, SOS_runtime::config, SOS_pub::data, SOS_pub::elem_count, SOS_pub::elem_max, SOS_data::guid, SOS_val::l_val, SOS_meta::layer, SOS_data::len, SOS_pub::meta, SOS_data::name, SOS_meta::nature, SOS_pub::node_id, SOS_config::node_id, SOS_time::pack, SOS_pub::pragma_len, SOS_pub::pragma_msg, SOS_meta::pri_hint, SOS_pub::process_id, SOS_pub::prog_name, SOS_pub::prog_ver, SOS_unique_set::pub, SOS_pub::pub_id, SOS_time::recv, SOS_meta::retain_hint, SOS_meta::scope_hint, SOS_time::send, SOS, SOS_LAYER_APP, SOS_next_id(), SOS_PRI_DEFAULT, SOS_RETAIN_DEFAULT, SOS_SCOPE_DEFAULT, SOS_SET_WHOAMI, SOS_STR_COPY_OF, SOS_VAL_STATE_EMPTY, SOS_data::state, SOS_pub::thread_id, SOS_data::time, SOS_pub::title, SOS_data::type, SOS_runtime::uid, and SOS_data::val.
SOS_pub* SOS_new_pub (char * title)
Definition at line 299 of file sos.c.
References dlog, and SOS_SET_WHOAMI.
Referenced by main(), and SOS_new_sub().
SOS_sub* SOS_new_sub ()
Definition at line 854 of file sos.c.
References SOS_sub::active, SOS_sub::pub, and SOS_new_pub().
long SOS_next_id (SOS_uid * id)
Definition at line 287 of file sos.c.
References SOS_uid::lock.
Referenced by SOS_new_post().
int SOS_pack (SOS_pub * pub, const char * name, SOS_val_type pack_type, SOS_val pack_val)
Definition at line 634 of file sos.c.
References SOS_pub::announced, SOS_val::c_val, SOS_pub::data, dlog, SOS_pub::elem_count, SOS_pub::elem_max, SOS_data::guid, SOS_val::i_val, SOS_val::l_val, SOS_data::name, SOS_time::pack, SOS_expand_data(), SOS_SET_WHOAMI, SOS_TIME, SOS_VAL_STATE_DIRTY, SOS_VAL_TYPE_DOUBLE, SOS_VAL_TYPE_INT, SOS_VAL_TYPE_LONG, SOS_VAL_TYPE_STRING, SOS_data::state, SOS_data::time, SOS_data::type, and SOS_data::val.
void SOS_post_to_daemon (char * msg, char * reply)
void SOS_publish (SOS_pub * pub)
Definition at line 1052 of file sos.c.
References SOS_pub::announced, SOS_val::c_val, SOS_pub::comm_rank, SOS_val::d_val, SOS_pub::data, dlog, SOS_pub::elem_count, SOS_data::guid, SOS_val::i_val, SOS_val::l_val, SOS_pub::meta, SOS_meta::nature, SOS_time::pack, SOS_pub::pub_id, SOS_runtime::role, SOS_time::send, SOS, SOS_announce(), SOS_DEFAULT_BUFFER_LEN, SOS_ROLE_CLIENT, SOS_SET_WHOAMI, SOS_TIME, SOS_VAL_STATE_CLEAN, SOS_VAL_TYPE_DOUBLE, SOS_VAL_TYPE_INT, SOS_VAL_TYPE_LONG, SOS_VAL_TYPE_STRING, SOS_data::state, SOS_data::time, SOS_data::type, and SOS_data::val.
void* SOS_refresh_sub (void * arg)
Definition at line 1233 of file sos.c.
References SOS_sub::active, and SOS_sub::refresh_delay.
void SOS_repack (SOS_pub * pub, int index, SOS_val pack_val)
Definition at line 805 of file sos.c.
References SOS_val::c_val, SOS_pub::data, SOS_time::pack, SOS_TIME, SOS_VAL_STATE_DIRTY, SOS_VAL_TYPE_DOUBLE, SOS_VAL_TYPE_INT, SOS_VAL_TYPE_LONG, SOS_VAL_TYPE_STRING, SOS_data::state, SOS_data::time, SOS_data::type, and SOS_data::val.
void SOS_send_to_daemon (char * msg, int msg_len, char * reply, int max_reply_size)
Definition at line 170 of file sos.c.
References SOS_runtime::net, SOS_socket_set::server_addr, server_socket_fd, SOS, and SOS_SET_WHOAMI.
void SOS_strip_str (char * str)
Definition at line 435 of file sos.c.
SOS_sub* SOS_subscribe (SOS_role source_role, int source_rank, char * pub_title, int refresh_delay)
Definition at line 1221 of file sos.c.
void * SOS_THREAD_post (void * arg)
Definition at line 236 of file sos.c.
References SOS, SOS_SET_WHOAMI, SOS_STATUS_RUNNING, and SOS_runtime::status.
Referenced by SOS_init().
void * SOS_THREAD_read (void * arg)
Definition at line 252 of file sos.c.
References SOS, SOS_SET_WHOAMI, SOS_STATUS_RUNNING, and SOS_runtime::status.
Referenced by SOS_init().
void * SOS_THREAD_scan (void * arg)
Definition at line 269 of file sos.c.
References SOS, SOS_SET_WHOAMI, SOS_STATUS_RUNNING, and SOS_runtime::status.
Referenced by SOS_init().
void SOS_unannounce (SOS_pub * pub)
Definition at line 1206 of file sos.c.
void SOS_unsubscribe (SOS_sub * sub)
Definition at line 1247 of file sos.c.