#!/bin/bash -e

# DISABLED! SEE https://github.com/ornladios/ADIOS/issues/48
rm -f gread_sample_data.ch
rm -f gwrite_sample_data.ch
gpp.py adios_config.xml

cd ../../src
if [ "$1" == "clean" ] ; then
    ./make clean
fi
./make
cd ../examples/synthetic_1
