#include "worker.h"
#include "stdio.h"
#include "stdlib.h"
#include "adios.h"

/* 
 * Worker A is the first application in the workflow.
 * It does some "computation" and communication for N
 * iterations, and it produces "output" that is "input" to worker_b.
 */

int iterations = 1;

void validate_input(int argc, char* argv[]) {
    if (argc < 2) {
        my_printf("Usage: %s <num iterations>\n", argv[0]);
        exit(1);
    }
    if (commsize < 2) {
        my_printf("%s requires at least 2 processes.\n", argv[0]);
        exit(1);
    }
    iterations = atoi(argv[1]);
}

int worker(int argc, char* argv[]) {
    my_printf("%d of %d In worker A\n", myrank, commsize);

    /* validate input */
    validate_input(argc, argv);

    my_printf("Worker A will execute %d iterations.\n", iterations);

    /* ADIOS: These declarations are required to match the generated
     *        gread_/gwrite_ functions.  (And those functions are
     *        generated by calling 'gpp.py adios_config.xml') ...
     */
    uint64_t  adios_groupsize;
    uint64_t  adios_totalsize;
    uint64_t  adios_handle;
    char      adios_filename[256];
    MPI_Comm  adios_comm;

    /* ADIOS: Can duplicate, split the world, whatever.
     *        This allows you to have P writers to N files.
     *        With no splits, everyone shares 1 file, but
     *        can write lock-free by using different areas.
     */
    MPI_Comm_dup(MPI_COMM_WORLD, &adios_comm);

    int NX = 10;
    int NY = 1;
    double t[NX];
    double p[NX];

    /* ADIOS: Set up the adios communications and buffers, open the file.
     */
    sprintf(adios_filename, "adios_a_to_b.bp");
    adios_init("adios_config.xml", adios_comm);

    int index, i;
    for (index = 0 ; index < iterations ; index++ ) {
        /* Do some exchanges with neighbors */
        do_neighbor_exchange();
        /* "Compute" */
        compute(index);
        /* Write output */
        //my_printf("a");

        for (i = 0; i < NX; i++) {
            t[i] = index*100.0 + myrank*NX + i;
        }

        for (i = 0; i < NY; i++) {
            p[i] = index*1000.0 + myrank*NY + i;
        }

        if (index == 0) {
            adios_open(&adios_handle, "a_to_b", adios_filename, "w", adios_comm);
        } else {
            adios_open(&adios_handle, "a_to_b", adios_filename, "a", adios_comm);
        }
        /* ADIOS: Set the value we wish to output into 'sample_var':
         */

        /* ADIOS: Actually write the data out.
         *        Yes, this is the recommended method, and this way, changes in
         *        configuration with the .XML file will, even in the worst-case
         *        scenario, merely require running 'gpp.py adios_config.xml'
         *        and typing 'make'.
         */
        //if (myrank == 0) {
            #include "gwrite_a_to_b.ch"
        //}
        /* ADIOS: Close out the file completely and finalize.
        *        If MPI is being used, this must happen before MPI_Finalize().
        */
        adios_close(adios_handle);
        MPI_Barrier(MPI_COMM_WORLD);
    }
    MPI_Barrier(MPI_COMM_WORLD);

    adios_finalize(myrank);
    my_printf("Worker A exting.\n");

    /* exit */
    return 0;
}
