#! /bin/sh

# Copyright (C) 2004 Oren Ben-Kiki.
# This library is distributed under a BSD-style license.
# See the COPYING file for details.

# Bootstrap the autotools after cleanup stripped the directory to the bare
# minimum. You don't need to run this unless you tinker with the autotools.
# Note specific autotools versions are used. If you use a different version
# you'll probably also have to change the configuration files.

echo "auxdir..."
rm -rf auxdir
mkdir auxdir \
    || { echo "mkdir auxdir failed"; exit 1; }
echo "aclocal..."
aclocal-1.8 \
    || { echo "aclocal failed"; exit 1; }
echo "autoheader..."
autoheader-2.59 --warnings=all \
    || { echo "autoheader failed"; exit 1; }
echo "automake..."
# --warnings=syntax complains about specifying a target more than once in
# order to collect a list of sub-targets. It seems to work fine anyway...
automake-1.8 --warnings=all --warnings=no-syntax --gnu --add-missing --copy \
    || { echo "automake failed"; exit 1; }
echo "autoconf..."
autoconf-2.59 --warnings=all \
    || { echo "autoconf failed"; exit 1; }
