#!/bin/bash
if [ "x${SOS_ROOT}" == "x" ] ; then
  echo "Please set the SOS_ROOT environment variable."
  kill -INT $$
fi
if [ "x${SOS_WORK}" == "x" ] ; then
  echo "Please set the SOS_WORK environment variable."
  kill -INT $$
fi
if [ "x${SOS_CMD_PORT}" == "x" ] ; then
  echo "Please set the SOS_CMD_PORT environment variable."
  kill -INT $$
fi
ls -AblFs $SOS_WORK/*.db
for db in $SOS_WORK/sosd.*.db ; do
    echo ""
    echo -n "${db} (daemon) [val.count] = "
    sqlite3 ${db} "select max(rowid) from tblvals;"
    echo -n "${db} (daemon) [pub.count] = "
    sqlite3 ${db} "select max(rowid) from tblpubs;"
    echo "${db} (daemon) [pubs.list] = "
    sqlite3 ${db}  -column -header "select row_id, guid, title, process_id, thread_id, comm_rank, node_id, prog_name from tblpubs where row_id in (select max(row_id) from tblpubs group by title, process_id, thread_id) order by prog_name, comm_rank, title;"
done

